server:
  port: 9002
  servlet:
    context-path: /
  tomcat:
    accesslog:
      enabled: true

spring:
  data:
    mongodb:
      database: orderDB
      host: 192.168.99.100
      port: 27017
      auto-index-creation: true

#keycloak:
#  realm: delivery-system-realm
#  auth-server-url: http://192.168.99.100:8080/auth
#  ssl-required: external
#  resource: ms-order
#  credentials:
#    secret: 50dba9f1-39fb-4762-86c8-eeb590a461cf
#  use-resource-role-mappings: true
#  bearer-only: true

logging:
  level:
    ROOT: INFO
    org.company.order: DEBUG
    org.mongodb.driver: DEBUG



